"BUG": "00 - Bug"
"ENH": "01 - Enhancement"
"MAINT": "03 - Maintenance"
"DOC": "04 - Documentation"
"TST": "05 - Testing"
"REF": "06 - Refactor"
"DEP": "07 - Deprecation"
"REL": "14 - Release"
"DEV": "16 - Development"
"WIP": "25 - WIP"
"API": "30 - API"
"REV": "34 - Reversion"
"BLD": "36 - Build"
