name: Project-Korora
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # test dependencies
  - pytest>=7.3.2

  # code checks
  - flake8=7.1
  - isort=6.0.1
  - black=24.2.0
  - pyupgrade=3.19.1

  # documentation
  - sphinx

  - pip:
    - pre-commit
