name: Set up Conda Environment
description: Sets up a Conda environment using the conda-incubator/setup-miniconda action.
inputs:
  auto-update-conda:
    description: 'Automatically update Conda'
    default: 'true'
  activate-environment:
    description: 'Name of the Conda environment to activate'
    default: 'Project-Korora'
  environment-file:
    description: 'Path to the Conda environment file'
    default: 'environment.yml'
runs:
  using: composite
  steps:
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: ${{ inputs.auto-update-conda }}
        activate-environment: ${{ inputs.activate-environment }}
        environment-file: ${{ inputs.environment-file }}
