name: Run Tests and Report Results
description: Action to run tests and handle test results
runs:
  using: composite
  steps:
    - name: Run tests with pytest
      run: |
        pytest --junitxml=test-data.xml
      shell: bash -el {0}

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: test-data.xml
      if: failure()
