on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Unit Tests

jobs:
  unit-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: ./.github/actions/setup-miniconda

      - name: Run Tests
        uses: ./.github/actions/run-tests
